### ISSUE TITLE
RPCServer throws exception due to thread check

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Decentred#7]
```
java.lang.IllegalStateException: net.openhft.chronicle.decentred.remote.rpc.RPCServer component which is not thread safes used by Thread[main,5,main] and Thread[main/test-1,1,main]
	at net.openhft.chronicle.core.io.AbstractCloseable.threadSafetyCheck(AbstractCloseable.java:339)
	at net.openhft.chronicle.core.io.AbstractCloseable.throwExceptionIfClosed(AbstractCloseable.java:254)
	at net.openhft.chronicle.decentred.remote.rpc.RPCServer$XCLConnectionListener.onMessage(RPCServer.java:222)
	at net.openhft.chronicle.decentred.remote.net.VanillaTCPServerConnection.onMessage(VanillaTCPServerConnection.java:59)
	at net.openhft.chronicle.decentred.remote.net.AbstractTCPConnection.processOneMessage(AbstractTCPConnection.java:131)
	at net.openhft.chronicle.decentred.remote.net.AbstractTCPConnection.readChannel(AbstractTCPConnection.java:108)
	at net.openhft.chronicle.decentred.remote.net.VanillaTCPServerConnection.run(VanillaTCPServerConnection.java:38)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:104)
```

in test `net.openhft.chronicle.decentred.server.DecentredClientServerTest#test`

**Comment by alamar** [comment]
Also `net.openhft.chronicle.decentred.server.RPCGatewayTest#endToEnd`
